# Generated by Django 4.2 on 2024-09-07 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_salesitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='pos.salesreport')),
            ],
        ),
        migrations.DeleteModel(
            name='SalesItem',
        ),
    ]
