# Generated by Django 4.2 on 2024-09-07 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_salesitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesitem',
            name='sales_report',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='SalesItem',
        ),
        migrations.DeleteModel(
            name='SalesReport',
        ),
    ]
